### PR TITLE
Remove properties

### PR DESCRIPTION
**Pull request by TobyEalden**
I'm not sure if this would generally be considered desired behaviour or not but thought I'd submit the PR anyway. 

I need to be able to remove a property from an object. I do this by setting the value to undefined.

### CODE REVIEW

**Comment by fresheneesz** [comment]
I think this should be ok. Thanks for the pull request!

**Comment by fresheneesz** [comment]
I'll try to put this change up on npm tomorrow

**Comment by fresheneesz** [comment]
Ok published to v1.1.0

**Comment by TobyEalden** [comment]
Thank you. I get a lot of use from this little library - nice work!

**Comment by fresheneesz** [comment]
Glad to hear it! Thanks!

**Pull request merged**
